version: "3.0"
services:
  load-balance:
    restart: "always"
    build: ./nginx
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - 9090:80

    networks:
      vpcbr:
        ipv4_address: 10.5.0.5  
        
        
        
   
  node1:
    restart: "always"
    build: ./app
    environment:
      - PORT=3001
      - SERVICE_NAME=node1
      - IP_ADDRESS=10.5.0.6

    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  node2:
    restart: "always"
    build: ./app
    environment:
      - PORT=3002
      - SERVICE_NAME=node2
      - IP_ADDRESS=10.5.0.7
    
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  node3:
    restart: "always"
    build: ./app
    environment:
      - PORT=3003
      - SERVICE_NAME=node3
      - IP_ADDRESS=10.5.0.8
      
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

    
   

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
